# -*- coding: utf-8 -*-
"""Ejercicios_1er_parcial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2EBSiyffwyE6-hXJzRvksr2_I6ITAVb

#**Ejercicios de parcial**

### **Ejercicio 1**

Escribir la función recursiva **parImpar(vector:np.array) → bool**, que dado un un arreglo “vector”, devuelve True si todos los elementos alternan entre par-impar (o impar-par). Las soluciones que NO sean recursivas no serán tomadas en cuenta.

Por ejemplo:

v1 = [4, 5, 10, 9, 8, 1, 12] => parImpar(v1) → True

v2 = [3, 10, 7, 9, 12, 15]  => parImpar(v2) → False
"""



"""### **Ejercicio 2**

En UNAHUR nos pidieron ayuda para poder tomar exámenes en los laboratorios.
Un examen tiene una fecha (se puede asumir que ya se tiene ese TDA con todas las operaciones necesarias) y un laboratorio con cierta capacidad. El laboratorio tiene una cantidad de hileras con mesas y cada hilera tiene la misma cantidad de mesas.

Lo que se necesita hacer es asignar una fecha al examen y en qué mesas se tiene que sentar cada alumno (Se debe sentar un alumno por mesa).

El criterio para “sentar” los alumnos es:

No puede haber 2 alumnos consecutivos en la misma hilera (no se puede tener a otro alumno a los lados).

Implementar el TDA **Examen** que contenga al menos las siguientes operaciones:

- **\_\_init\_\_(self,fecha:Fecha, hileras:int, mesas:int)** Que recibe la fecha, la cantidad de hileras y la cantidad de mesas por hilera del laboratorio.
- **asignarLugares(self, cantAlumnos:int):** Que recibe la cantidad de alumnos que se desean acomodar y los acomoda en el laboratorio. Asumir que la cantidad de alumnos entran de manera que estén separados con el criterio establecido.
- **empezarDeNuevo(self)**: Que deja el laboratorio sin asignar (vacío).
"""



"""### **Ejercicio 3**

Implementar la función **recursiva** **"inversionRecursiva"** que recibe por parámetro un string y retorna un nuevo string conteniendo el string de entrada invertido.

Por ejemplo:

Si str1 = "hola"

str2 = inversionRecursiva(str1)

Entonces, str2 = "aloh"  

"""



"""### **Ejercicio 4**

Un chef está intentando organizar sus recetas y necesita ayuda mediante algún registro de datos. Para esto decide crear una aplicación, para la que se deben modelar este tipo de datos. Crear el TDA **"Receta"**, que contiene una arreglo con los ingredientes de una receta, el nombre de la receta y el tipo (Puede ser “omnivora”, “vegetariana” o “vegana” ).
Los ingredientes se definen con los siguientes componentes:
*  Nombre
*  Cantidad (valor entero)
*  Calorías que aporta a la receta

Una Receta puede tener a lo sumo 20 ingredientes

Implementar las siguientes operaciones:
* **\_\_init\_\_(self, nombre:str, tipo:str)**: Crea una receta
*  **cantidadDeIngredientes(self)->int**: Retorna la cantidad de ingredientes de la receta
*  **registrarIngrediente(self, nombre:str, cantidad:int, calorias:float)**: Agrega un ingrediente a la receta
*  **totalCalorias(self)->float**: Retorna el total de las calorías de la receta
*  **ingredienteMasCalorico(self)->Ingrediente**: Retorna el ingrediente con mayor cantidad de calorías de la receta
"""



"""### **Ejercicio 5**

Escribir la función ***recursiva*** **"sonIguales"** que recibe dos strings del mismo tamaño (no vacías) y retorna *True* si son iguales y *False* en caso contrario.
"""



"""### **Ejercicio 6**

En UNAHUR se está desarrollando un software para administrar el estacionamiento. En todo momento pueden entrar o salir autos. No puede haber dos autos en el mismo lugar y de cada auto solo nos interesa conocer la patente y la hora de ingreso, que a fines prácticos consideraremos dos números.

Al inicio del día se puede asumir que el estacionamiento comienza vacío y con una cantidad fija de lugares que informa el bedel al abrir el lugar. Vamos a suponer que el estacionamiento tiene igual cantidad de espacios verticales que horizontales cada día. Por ejemplo 20x20 lugares. Lo que se necesita hacer es asignar un auto a algún lugar vacío cada vez que ingresa y desasignarlo cuando egresa.

Implementar el TDA EstacionamientoUnaHur que contenga al menos las siguientes operaciones:

- **\_\_init\_\_(self, cantLugares:int):** Recibe la cantidad total de lugares en el estacionamiento y crea una variable de tipo EstacionamientoUnaHur.
- **estacionar(self, patente:int, horaIngreso:int)->tuple[int,int]:** Estaciona el auto en algún lugar disponible. La función debe retornar la ubicación (posición vertical y posición horizontal) utilizada. Si no hay más lugar debe lanzar una excepción. Se puede asumir que no se estacionan dos autos iguales ni estacionan dos autos al mismo tiempo.
- **salir(self, patente:int)->int:** Libera el espacio si el auto se encuentra en el estacionamiento y retorna la hora de ingreso. Si el auto no se encuentra en el estacionamiento no debe hacer nada.
- **estaVacio(self)->bool:** Retorna True si no hay ningún auto estacionado y False en caso contrario.
- **cantidadAutosHora(self, hora:int)->int:** Devuelve la cantidad de autos que ingresaron antes de la hora recibida por parámetro y que aún están en el estacionamiento.

"""

import numpy as np
class Auto:
  def __init__(self, patente:int, hora:int):
    self.__patente = patente
    self.__hora = hora

class Estacionamiento:
  def __init__(self, cantLugares:int):
    self.__lugares = np.empty((np.sqrt(cantLugares), np.sqrt(cantLugares)), Auto)

"""### **Ejercicio 7**

Escribir la función recursiva **estaIncluido(arreglo1, arreglo2)**, que retorna verdadero si el arreglo1 está incluido al inicio o al final del arreglo2. Tener en cuenta que un arreglo vacío siempre está incluido en otro (vacío o no) y que un arreglo vacío solo puede incluir a otro vacío. Soluciones que no sean recursivas NO serán tenidas en cuenta.

Por ejemplo, si:

arr1 = [2, 5, 1], arr2 = [1, 9, 3, 4, 2, 5, 1] , arr3 = [2, 5, 1, 6 ,1, 8, 5] , arr4 = [4, 3, 2, 5, 1, 8, 2]

estaIncluido(arr1, arr2) => True

estaIncluido(arr1, arr3) => True

estaIncluido(arr1, arr4) => False

Ayuda: Pueden utilizar dos funciones auxiliares, al menos una tiene que ser recursiva.
"""



"""### **Ejercicio 8**

El gobierno de un país cambia de idea y decide comenzar a atender la salud pública de sus habitantes, para esto decide desarrollar un software para optimizar el funcionamiento de los hospitales públicos. Implementar el TDA Sala que modela una sala de internación de un hospital, con N filas con M camas cada una. En cada cama se ubicará un Paciente, que se define con el DNI, la matrícula del médico que lo atiende y un diagnóstico, que puede ser: “grave” o “leve”.  
Al ubicar pacientes en la sala, tendremos en cuenta el diagnóstico, a pacientes “graves” los tenemos que ubicar cerca de las puertas de la sala (primera o última fila), mientras que los pacientes en estado “leve” solo pueden ir en el resto de la sala.  

**Nota**: Implementar el TDA Paciente con las operaciones necesarias. Pueden suponer que la cantidad de filas siempre es mayor o igual a 3 (al menos 2 filas de camas para graves y 1 para leves).

Implementar el TDA Sala que contenga al menos las siguientes operaciones:

- **\_\_init\_\_(self, cantFilas:int, cantCamas:int)**: que recibe la cantidad de filas y cantidad de camas por fila y crea una variable de tipo Sala.
- **ingresarPaciente(self, dni:int, medico:int, diagnóstico:str)**: que recibe los datos de un paciente y lo ubica en la sala. Arroja una excepción si el paciente no puede ser ubicado, por ejemplo porque es un paciente grave y los lugares correspondientes están llenos.
- **mismoMedico(self, filaN:int) → bool**: que devuelve True si en la fila “filaN” hay dos pacientes (o más) contiguos que los atienda el mismo médico.

### **Ejercicio 9**

Escribir las funciones que considere necesarias para implementar un algoritmo recursivo que cuente la cantidad de números pares y otro algoritmo recursivo para contar la cantidad de números mayores que 10 en un arreglo de números enteros. Por último implementar la función  masParesQue10(arreglo), que devuelve True cuando “arreglo” tiene más números pares que números mayores que 10. Esta última función no hace falta que sea recursiva. Las soluciones que NO sean recursivas no serán tomadas en cuenta.
"""

